services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-devsys
      MONGO_INITDB_ROOT_PASSWORD: d3vsys

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-devsys
      ME_CONFIG_MONGODB_ADMINPASSWORD: d3vsys
      ME_CONFIG_MONGODB_URL: mongodb://mongo-devsys:d3vsys@mongo:27017/
